version: '3'

services:
  api:
    build: ./api
    container_name: api
    ports:
      - '8000:8000'
    volumes:
      - ./api:/var/www/html
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - api